# development.ini Configure app behavior
[app:main]
use = egg:politecheck#main
pyramid.reload_templates = true
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

[loggers]
keys = root, request

[handlers]
keys = console

[formatters]
keys = json

[logger_root]
level = INFO
handlers = console

[logger_request]
level = INFO
handlers = console
qualname = request
propagate = 0

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = INFO
formatter = json

[formatter_json]
format = {"time": "%(asctime)s", "level": "%(levelname)s", "message": "%(message)s", "meta": "%(structured)s"}