apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "politecheck.fullname" . }}-config
  labels:
    {{- include "politecheck.labels" . | nindent 4 }}
data:
  POLITECHECK_ENV: "prod"
  REDIS_HOST: "{{ include "politecheck.fullname" . }}-redis-master"
  REDIS_PORT: "{{ .Values.redis.service.port }}"
  REDIS_DB: "0"
  {{- if .Values.redis.auth.enabled }}
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  {{- end }}
  
  TISANE_BASE_URL: "{{ .Values.tisane.baseUrl }}"
  
  LOG_LEVEL: "{{ .Values.backend.logging.level | default "INFO" }}"
  
  APP_NAME: "{{ include "politecheck.name" . }}"
  APP_VERSION: "{{ .Chart.AppVersion }}" 