{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "politecheck.fullname" . }}-redis
  labels:
    {{- include "politecheck.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "politecheck.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }} 